[tool.poetry]
name = "libhockey"
version = "0.22.0"
description = "A Python wrapper around the Hockey App API."

license = "MIT"

authors = [
    "Dale Myers <dalemy@microsoft.com>"
]

readme = 'README.md'

repository = "https://github.com/Microsoft/libhockey"
homepage = "https://github.com/Microsoft/libhockey"

keywords = ['hockey', 'hockeyapp', 'api']

classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development',
    'Topic :: Utilities'
]

[tool.poetry.dependencies]
python = "^3.6"
deserialize = "^0.10.0"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
mypy = "=0.730"
pylint = "=2.4.2"
pytest = "=4.0.1"
pytest-cov = "=2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
