[tool.poetry]
name = "bluestoned"
version = "0.1.0"
description = "find bluescreen chroma keys or other color rangers in video files and images using OpenCV"
authors = ["Nik Cubrilovic <git@nikcub.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
opencv-python = "^4.1"
numpy = "^1.17"
tqdm = "^4.36"
verboselogs = "^1.7"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
isort = "^4.3"

[tool.poetry.scripts]
bluestoned = 'bluestoned.main:cli'

[tool.black]
line-length = 90
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
